print('**************************************')
print('             PROGRAM PYTHON               ')
print('          OLEH: RESNA RAHMAWATI')
print('          KELAS: X PPLG 2')
print('**************************************')